import { useEffect } from "react";
import { useAtom } from "jotai";
import type { GetServerSideProps } from "next";
import Head from "next/head";
import UserDetailsAtom from "../atoms/UserDetailsAtom";
import type UserData from "../models/UserData";
import { getServerAuthSession } from "../server/common/get-server-auth-session";
import { prisma } from "../server/db/client";

interface Props {
  userData: UserData;
}

const Home = ({ userData }: Props) => {
  const [_, setUserData] = useAtom(UserDetailsAtom);

  useEffect(() => {
    setUserData(userData);
  }, []);

  const greeting = () => {
    const currentDate = new Date();
    const hour = currentDate.getHours();

    let format = "";
    if (hour >= 6 && hour < 11) {
      format = "Good morning";
    } else if (hour >= 11 && hour < 16) {
      format = "Good day";
    } else if (hour >= 16 && hour <= 18) {
      format = "Good evening";
    } else {
      format = "Good night";
    }

    return `${format}, ${userData.firstName}`;
  };

  return (
    <>
      <Head>
        <title>Weight Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="bg-slate-50 py-2 text-center text-3xl font-bold">
          {greeting()}
        </h1>

        <div className=""></div>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getServerAuthSession({ req, res });

  if (!session?.user) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  const userData = await prisma.users.findFirst({
    where: {
      id: session.user?.id,
    },
  });

  return {
    props: {
      userData: {
        id: userData?.id,
        firstName: userData?.first_name,
        lastName: userData?.last_name,
        email: userData?.email,
        sex: userData?.sex,
        dob: userData?.dob?.toUTCString(),
        avatarUrl: userData?.avatar_url,
      },
    },
  };
};

export default Home;
